## Load in SNP data to a snpMatrix object in order to do basic HWE and MAF quality control ##

source("/chiswick/data/ncooper/ImmunochipReplication/Scripts/FunctionsCNVAnalysis.R")
source("/chiswick/data/ncooper/ImmunochipReplication/Scripts/DefineDirectoriesLocations.R")

must.use.package("limma",T)
must.use.package("snpStats",T)

# INSTRUCTIONS #
# Need the files generated by bash import script
# Must have files: subIdsALL.txt, snpNames.txt, in location 'dir$ano'
# Must have file: file.lengths.txt, file.spec.txt in location 'dir$col' (column data directory)
# output location of main data files: /CALLRATE
# can run QC in R in either HD=T (Slow, low RAM requirement) or HD=F (Fast, high RAM)
# or, QC can be run in plink and this will provide summary, and generate corresponding R objects

# EXAMPLE COMMANDS:
# R --no-save --slave < LoadInSnps.R PLINK=0 HD=0  # normal, fast R import
# R --no-save --slave < LoadInSnps.R PLINK=0 HD=1  # low ram/slow R import 
# R --no-save --slave < LoadInSnps.R PLINK=1 HD=0  # low ram/fast, QC done with plink

##### DEFAULT OPTIONS (can modify via command line args) #####
import.plink <- T  # QC has been done in plink, just import these summary files
# dir$ano # annotation directory
# dir$col # column data directory
# dir$cr  # call-rate directory (SNP-QC)
drawVennsOfHWEvsCR <- T   # draw venn diagrams of HWE vs MAF vs CAll rate
doDensityPlots <- T  # visualise call rate distributions.
restore.mode <- F  # whether to run in restore mode, which means start by loading raw snpMatLst
HD.mode <- F  # whether to process list of SnpMatrix objects in memory or on disk (RAM dependent)
use.multi <- F
callrate.samp.thr <- .95   # minimum call rate threshold for samples
callrate.snp.thr <- .95   # minimum call rate threshold for snps
hwe.thr <- 10^-7   # minimum call rate threshold for snps

### CUSTOM USER OPTIONS ###
# can customize these but if using standard scripts these shouldn't change #
tabulateCallRate <- T # table of call rate exclusion %'s for snps and samples
mm <- "map3"  # format for SNP info file
snp.info.fn <- paste(dir$ano,"rawdata.map",sep="")
sample.fn <- "subIdsALL.txt" # sample ids (assuming in annotation directory, dir$ano) 
snp.fn <- "snpNames.txt" # snp labels (assuming in annotation directory, dir$ano)
file.loc <- paste(dir$cr,"snpMatLst.RData",sep="") # location to save list of snp matrix objects
# text files for QC results outputted are: "sampleqc.txt", "snpqc.txt"
#########################

## COMMAND LINE ##
arg.list <- parse.args(commandArgs(),coms=c("PLINK","HD","MULTI","RESTORE","DENS","VENN","HWE","SAMPCR","SNPCR"),
                       def=c(paste(as.integer(c(import.plink,HD.mode,use.multi,restore.mode,doDensityPlots,drawVennsOfHWEvsCR))),
                             paste(c(hwe.thr,callrate.samp.thr,callrate.snp.thr))))

if (!is.null(arg.list))
{
  print(arg.list)
  # override options in file if entered at the command line (unix)
  if (arg.list["PLINK",] %in% paste(c(0,1))) { import.plink <- as.logical(as.numeric(arg.list["PLINK",][1])) }
  if (arg.list["HD",] %in% paste(c(0,1))) { HD.mode <- as.logical(as.numeric(arg.list["HD",][1])) }
  if (arg.list["MULTI",] %in% paste(c(0,1))) { use.multi <- as.logical(as.numeric(arg.list["MULTI",][1])) }
  if (arg.list["DENS",] %in% paste(c(0,1))) { doDensityPlots <- as.logical(as.numeric(arg.list["DENS",][1])) }  
  if (arg.list["RESTORE",] %in% paste(c(0,1))) { restore.mode <- as.logical(as.numeric(arg.list["RESTORE",][1])) }
  if (arg.list["VENN",] %in% paste(c(0,1))) { drawVennsOfMAFvsHWEvsCR <- as.logical(as.numeric(arg.list["VENN",][1])) }
  if (abs(as.numeric(arg.list["HWE",]))<1) { hwe.thr <- abs(as.numeric(arg.list["HWE",][1])) }
  if (nchar(arg.list["SAMPCR",])<=1) { callrate.samp.thr <- (paste(arg.list["SAMPCR",][1])) }
  if (nchar(arg.list["SNPCR",])<=1) { callrate.snp.thr <- (paste(arg.list["SNPCR",][1])) }
} 
#################################

# a typical call, allowing defaults for most parameters
#load.in.snps(import.plink=T,HD.mode=F,restore.mode=F,dir)
  

load.in.snps <- function(dir, import.plink=F, HD.mode=F, restore.mode=F,
                         callrate.samp.thr=.95, callrate.snp.thr=.95, hwe.thr=10^-7,
                         tabulateCallRate=T, use.multi=F, drawVennsOfHWEvsCR=T,
                         doDensityPlots=T, mm="map3", snp.info.fn="rawdata.map",
                         sample.fn = NULL, snp.fn="snpNames.txt",
                         file.loc="snpMatLst",...)
{
  if(use.multi) {  must.use.package("multicore",F) }
  # test for 
  if(restore.mode & import.plink) { cat("setting RESTORE=0, not compatible with PLINK=1\n"); restore.mode <- F }
  if(HD.mode & import.plink) { cat("setting HD=0 because HD=1 is not compatible with PLINK=1\n"); HD.mode <- F }
  dir <- validate.dir.for(dir,c("ano","cr","raw","col","cr.plk","ids"),warn=T)
  file.loc <- dir.fn.cmb(dir$cr,file.loc,ext=".RData")
  snp.info.fn <- dir.fn.cmb(dir$ano,snp.info.fn,must.exist=T)
           
  # read in snp list 
  if (snp.fn %in% list.files(dir$ano)) {
    snpIDs <- readLines(dir.fn.cmb(dir$ano,snp.fn))
  } else {
    linez <- character()
    linez[1] <- paste("Error: expecting file: '",snp.fn,"' in ",dir$ano,".",sep="")
    linez[2] <- "This file speeds up import by giving the snp order in the raw file"
    linez[3] <- "File should be generated using the bash command:"
    linez[4] <- paste("grep <anySampleid> <mydatafiles> | cut -f 2 | cat >",snp.fn)
    cat(linez,"\n")
    stop()
  }    
  
  # load and prepare SNP info object
  CHR.INFO <- calc.chr.ind(dir, snp.fl=snpIDs, mode=mm, 
                           vcf.fn=snp.info.fn, sav=F,... )
  
  snp.info <- convert.chr.obj.IRanges(CHR.INFO)
  
  if (!import.plink & !restore.mode) 
  { 
    # RESTORE = 0, PLINK = 0 #
    cat("\nImporting SNP data into R using snpStats package\n")
    snpMatLst <- import.snp.matrix.list(snpIDs,dir=dir,HD=HD.mode,multi=use.multi) 
    if(!HD.mode) { save(snpMatLst,file=file.loc); cat(paste("saved snpMatLst to",file.loc,"\n")) }
    snpMatLst <- sync.snpmat.with.info(snpMatLst,snp.info,sample.info=NULL) 
  } else { 
    if(restore.mode)
    {
      if(!HD.mode & file.exists(file.loc)) {
        # RESTORE = 1, PLINK = 0, HD = 0, file.loc exists #
        cat(paste("\nRestoring SnpMatrix list from",file.loc,"\n"))
        snpMatLst <- get(paste(load(file.loc)))
        snpMatLst <- sync.snpmat.with.info(snpMatLst,snp.info,sample.info=NULL)
      } else {
        # RESTORE = 1, PLINK = 0, HD = 1 or file.loc doesn't exist #
        if(HD.mode & file.exists(paste(dir$cr,"snpMat",1,".RData",sep=""))) {
          cat(paste("\nRestoring multiple SnpMatrix files from",paste("snpMat*.RData\n")))
          existo <- T; cnt <- 1; snpMatLst <- list()
          while(existo){
            nfn <- paste(dir$cr,"snpMat",cnt,".RData",sep="")
            if (file.exists(nfn)) 
            { snpMatLst[[cnt]] <- nfn ; cnt <- cnt+1 
            } else {
              existo <- F
            }
          }
          snpMatLst <- sync.snpmat.with.info(snpMatLst,snp.info,sample.info=NULL)
        } else {
          # RESTORE = 1, PLINK = 0, no snpMat*RData files exist #
          stop("Restore mode failed, expected .RData files not present\n")
          snpMatLst <- NULL
        }
      }
    } else {
      # RESTORE = 0, PLINK = 1 #
      cat("\nUsing Plink QC files as input\n")
      snpMatLst <- NULL 
    }
  }
  
  # read in subject list
  if(is.null(sample.fn)) {
    subIDs.actual <- get.subIDs(dir,"combined")
  } else {
    if ((rmv.dir(sample.fn) %in% c(list.files(dir$ids))) | file.exists(sample.fn)) {
      subIDs.actual <- readLines(dir.fn.cmb(dir$ano,sample.fn))
      num.subs <- length(subIDs.actual)
      if(num.subs==0) {
        stop(paste("Error: no subject IDs found in file: '",sample.fn,"' in ",dir$ano,".",sep=""))
      }
    } else {
      subIDs.actual <- get.subIDs(dir,"combined")
    }
  }
  
  samp.qc.list <- doSampQC(dir, plink=import.plink,
                           callrate.samp.thr, snpMatLst, subIDs.actual)
  
  sample.info <- samp.qc.list$SAMPLE.INFO
  
  # Tabulate sample call rate stats
  if(tabulateCallRate) {  samp.result <- call.rate.summary(sample.info) }
  
  # write sample call rate failure lists to text file #
  ofn <- paste(dir$cr,"sampleqc.txt",sep="")
  write.table(sample.info,file=ofn,sep="\t")
  cat(paste("wrote file with samples call rate QC summary to:\n",ofn,"\n"))
  ofn <- paste(dir$ano,"SAMPLE_EXCLUDE/callrate.txt",sep="")
  writeLines(samp.qc.list$CR.EXCL,con=ofn)
  cat(paste("wrote file with samples to exclude because of low call rate:\n",ofn,"\n"))
  
  if(!import.plink) { snpMatLst <- sync.snpmat.with.info(snpMatLst,infoRange=NULL,sample.info[sample.info$QCfail==0,]) } 
  
  snp.qc.list <- doSnpQC(dir, plink=import.plink,
                         callrate.snp.thr=.95, hwe.thr=hwe.thr,
                         snpMatLst, subIDs.actual, snp.info)
  
  snp.info <- snp.qc.list$SNP.INFO
  
  # Tabulate snp call rate stats
  if(tabulateCallRate) {  snp.result <- call.rate.summary(snp.info) }
  
  ofn <- paste(dir$cr,"snpqc.txt",sep="")
  write.table(as.data.frame(snp.info[,c("call.rate","P.hwe","QCfail")]),file=ofn,sep="\t")
  cat(paste("wrote file with snp call rate and HWE QC summary to:\n",ofn,"\n"))
  ofn=paste(dir$ano,"SNP_EXCLUDE/callrate.txt",sep="")
  writeLines(snp.qc.list$CR.EXCL,con=ofn)
  cat(paste("wrote file with call rate failing snps to:\n",ofn,"\n"))
  writeLines(snp.qc.list$HWE.EXCL,con=paste(dir$ano,"SNP_EXCLUDE/HWE.txt",sep=""))
  cat("wrote HWE exclusion list to annotion directory\n")
  
  ## REMOVE MISSING VALUES, STORING ORIGINALS ##
  # note that graphing and tables below work poorly with missing
  snp.info.orig <- snp.info
  if(nrow(snp.info.orig[!is.na(snp.info.orig[,1]),])>(length(snpIDs)/2))
  {
    # so long as there are a reasonable number of snps here, replace sort list 
    # in annotation directory with the sorted list just derived
    # (prevents replacement in most cases of crash/incorrect input)
    dest.dir <- paste(dir$ano,"SNP_SORT/",sep="")
    unlink(list.files(dest.dir))
    cat("replacing any files in directory ANNOTATION/SNP_SORT/ with new sorted snp list\n")
    ofn <- paste(dest.dir,"snpsort.txt",sep="")
    writeLines(rownames(snp.info.orig),con=ofn)
    cat("wrote file:",ofn,"\n")
  } else {
    cat("Warning: number of valid snps in 'snp.info' object is less than half of original list, please check files!")
  }
  
  removeNAs <- F
  if(removeNAs) {
    # don't think this is necessary....
    snp.info <- snp.info[!is.na(snp.info$call.rate),]
    sample.info.orig <- sample.info
    sample.info <- sample.info[!is.na(sample.info$call.rate),]
  }

  # View overlap of call rate and HWE exclusion criteria for SNPs
  if(drawVennsOfHWEvsCR) {
    cat(" generating venn diagrams\n")
    conds <- cbind(snp.qc.list$CR.cond,snp.qc.list$HWE.cond)
    conds[is.na(conds)] <- FALSE; vc <- vennCounts(conds) ; vc
    ofn <- paste(dir$cr,"venn_",(100*callrate.snp.thr),".pdf",sep="")
    pdf(ofn)
    vennDiagram(vc,names=c(paste("Call rate<.",callrate.snp.thr,sep=""),paste("HWE p<",hwe.thr,sep="")))
    dev.off()
    cat(paste("wrote Venn figure to file:",ofn,"\n"))
  }
  
  # Visualize call rate stats
  if(doDensityPlots) {
    fn <- paste(dir$cr,"callRateDistributionsAnnotated.pdf",sep="")
    draw.density.plots(fn,sample.info,snp.info,samp.result,snp.result,
                       callrate.samp.thr=callrate.samp.thr, callrate.snp.thr=callrate.snp.thr)
  }
  outlist <- list(sample.info,snp.info)
  names(outlist) <- c("sample.info","snp.info")
  return(outlist)
}

preload.bioC()

wait(.006,"m",F)

## RUN COMMAND USING COMMAND LINE or default SETTINGS ##
#sample.snp <- load.in.snps(import.plink=F,HD.mode=F,restore.mode=F,
#             callrate.samp.thr,callrate.snp.thr,hwe.thr=10^-8,dir=dir,
#             tabulateCallRate,use.multi,drawVennsOfHWEvsCR,doDensityPlots,
#             mm,snp.info.fn,sample.fn,snp.fn)

sample.snp <- load.in.snps(dir=dir,hwe.thr=10^-8)

save(sample.snp,file=paste(dir$ano,"samplensnp.RData",sep=""))
print("saved samplensnp.RData")


## END ##
